# Generated by Django 3.2.7 on 2021-10-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='marketing_price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='promotional_marketing_price',
            field=models.FloatField(default=0, verbose_name='Promotional Price'),
        ),
    ]
