# Generated by Django 3.2.7 on 2021-09-17 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('status', models.CharField(choices=[('A', 'Approved'), ('R', 'Rejected'), ('C', 'Created'), ('P', 'Pending'), ('S', 'Sent'), ('F', 'Finished')], default='C', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemandItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('product_id', models.PositiveIntegerField()),
                ('variation', models.CharField(max_length=255)),
                ('variation_id', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('promotional_price', models.FloatField(default=0)),
                ('amount', models.PositiveIntegerField()),
                ('image', models.CharField(max_length=2000)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demand.demand')),
            ],
            options={
                'verbose_name': 'Request item',
                'verbose_name_plural': 'Request items',
            },
        ),
    ]
