# Generated by Django 3.2.7 on 2021-11-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_forget_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='forget_password_token',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
