# Generated by Django 3.2.7 on 2021-11-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userprofile_forget_password_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='forget_password_token',
        ),
    ]
