# Generated by Django 3.2.7 on 2021-11-08 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_userprofile_forget_password_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
    ]
